CREATE TABLE IF NOT EXISTS SA_USER
(
    ID  UUID PRIMARY KEY,
    PHONE   CHAR(10),
    EMAIL   VARCHAR(320),
    FIRST_NAME  VARCHAR(50),
    LAST_NAME   VARCHAR(50),
    MIDDLE_NAME VARCHAR(50),
    BIRTH_DATE  DATE,
    COUNTRY     VARCHAR(100),
    STATUS      VARCHAR(20),
    CREATED_AT  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX UID_SA_USER_PHONE ON SA_USER(PHONE);
CREATE UNIQUE INDEX UID_SA_USER_EMAIL ON SA_USER(EMAIL);
CREATE INDEX  IDX_SA_USER_LAST_NAME ON SA_USER(LAST_NAME);
